# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: DeRain
model_type: ImageRestorationModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DeRain_train
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/DERAIN/DATA_20220325/train/gt
    dataroot_lq: /content/drive/MyDrive/DERAIN/DATA_20220325/train

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 512
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DeRain_train
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/DERAIN/DATA_20220325/validate/gt
    dataroot_lq: /content/drive/MyDrive/DERAIN/DATA_20220325/validate
    io_backend:
      type: disk

# network structures
network_g:
  type: HINet
  wf: 64
  hin_position_left: 0
  hin_position_right: 4


# path
path:
  models: logs/models
  training_states: logs/training_states
  # pretrain_network_g: ~
  pretrain_network_g: experiments/pretrained_models/trained.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: 10000 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 0.5
    reduction: mean
#    toY: true

# validation settings
val:
#  val_freq: 10
#  val_freq: !!float 2.5e4
  val_freq: 1000
  save_img: false
  grids: true
  crop_size: 512
  max_minibatch: 2

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
